// <auto-generated />
using System;
using LogNow.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogNow.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LogNow.API.Models.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolutionBreached")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResponseBreached")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OnHoldReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolutionDueAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResponseDueAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IncidentNumber")
                        .IsUnique();

                    b.HasIndex("ServiceId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("LogNow.API.Models.IncidentComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("UserId");

                    b.ToTable("IncidentComments");
                });

            modelBuilder.Entity("LogNow.API.Models.IncidentTimeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("UserId");

                    b.ToTable("IncidentTimelines");
                });

            modelBuilder.Entity("LogNow.API.Models.SLA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResolutionTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResponseTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Severity")
                        .IsUnique();

                    b.ToTable("SLAs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9acc7dac-28f4-4868-be05-4140f04e8d99"),
                            CreatedAt = new DateTime(2026, 2, 21, 3, 25, 55, 853, DateTimeKind.Utc).AddTicks(1135),
                            ResolutionTimeMinutes = 30,
                            ResponseTimeMinutes = 5,
                            Severity = "SEV1"
                        },
                        new
                        {
                            Id = new Guid("63ffb8ac-2987-45b4-872b-7ce837d3ab75"),
                            CreatedAt = new DateTime(2026, 2, 21, 3, 25, 55, 853, DateTimeKind.Utc).AddTicks(1164),
                            ResolutionTimeMinutes = 120,
                            ResponseTimeMinutes = 15,
                            Severity = "SEV2"
                        },
                        new
                        {
                            Id = new Guid("727bee93-794c-4498-b66b-8c7cdf0d54ad"),
                            CreatedAt = new DateTime(2026, 2, 21, 3, 25, 55, 853, DateTimeKind.Utc).AddTicks(1177),
                            ResolutionTimeMinutes = 1440,
                            ResponseTimeMinutes = 60,
                            Severity = "SEV3"
                        },
                        new
                        {
                            Id = new Guid("aac367c7-a923-428a-ac29-1acceb0476b7"),
                            CreatedAt = new DateTime(2026, 2, 21, 3, 25, 55, 853, DateTimeKind.Utc).AddTicks(1179),
                            ResolutionTimeMinutes = 4320,
                            ResponseTimeMinutes = 240,
                            Severity = "SEV4"
                        });
                });

            modelBuilder.Entity("LogNow.API.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("LogNow.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LogNow.API.Models.Incident", b =>
                {
                    b.HasOne("LogNow.API.Models.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogNow.API.Models.User", "AssignedToUser")
                        .WithMany("AssignedIncidents")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogNow.API.Models.User", "CreatedByUser")
                        .WithMany("CreatedIncidents")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogNow.API.Models.Service", "Service")
                        .WithMany("Incidents")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("LogNow.API.Models.IncidentComment", b =>
                {
                    b.HasOne("LogNow.API.Models.Incident", "Incident")
                        .WithMany("Comments")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogNow.API.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogNow.API.Models.IncidentTimeline", b =>
                {
                    b.HasOne("LogNow.API.Models.Incident", "Incident")
                        .WithMany("Timeline")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogNow.API.Models.User", "User")
                        .WithMany("TimelineActions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Incident");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogNow.API.Models.Incident", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("LogNow.API.Models.Service", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("LogNow.API.Models.User", b =>
                {
                    b.Navigation("AssignedIncidents");

                    b.Navigation("Comments");

                    b.Navigation("CreatedIncidents");

                    b.Navigation("TimelineActions");
                });
#pragma warning restore 612, 618
        }
    }
}
